name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pyinstaller
        
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd app
        pyinstaller --onefile --windowed --name="剂量验证预测系统" --add-data="model_loader.py;." gui_fixed.py
        
    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd app
        pyinstaller --onefile --windowed --name="剂量验证预测系统" --add-data="model_loader.py:." gui_fixed.py
        
    - name: Build executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd app
        pyinstaller --onefile --name="剂量验证预测系统" --add-data="model_loader.py:." gui_fixed.py
        
    - name: Create release package
      run: |
        mkdir release
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp app/dist/剂量验证预测系统.exe release/
          echo "ASSET_NAME=剂量验证预测系统-windows.exe" >> $GITHUB_ENV
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          cp -r app/dist/剂量验证预测系统.app release/ || cp app/dist/剂量验证预测系统 release/
          tar -czf release/剂量验证预测系统-macos.tar.gz -C release .
          echo "ASSET_NAME=剂量验证预测系统-macos.tar.gz" >> $GITHUB_ENV
        else
          cp app/dist/剂量验证预测系统 release/
          tar -czf release/剂量验证预测系统-linux.tar.gz -C release .
          echo "ASSET_NAME=剂量验证预测系统-linux.tar.gz" >> $GITHUB_ENV
        fi
      shell: bash
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-executable
        path: release/ 