name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        
    - name: Build Windows executable
      run: |
        cd app
        python build_executable.py
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1
        
    - name: Create Windows release package
      run: |
        mkdir release
        
        REM Copy Windows executable file
        copy "app\dist\DoseVerificationSystem.exe" "release\" 2>nul || copy "app\dist\*.exe" "release\"
        
        REM Create Windows usage instructions
        echo Dose Verification System - Windows Version > release\README.txt
        echo Build time: %date% %time% >> release\README.txt
        echo. >> release\README.txt
        echo Usage Instructions: >> release\README.txt
        echo 1. Download and extract this file >> release\README.txt
        echo 2. Place your model files (result directory) in the same directory as the executable >> release\README.txt
        echo 3. Double-click to run DoseVerificationSystem.exe >> release\README.txt
        echo. >> release\README.txt
        echo Note: Model files need to be provided separately, not included in this package >> release\README.txt
        echo. >> release\README.txt
        echo System Requirements: >> release\README.txt
        echo - Windows 10/11 >> release\README.txt
        echo - At least 4GB RAM >> release\README.txt
        echo - At least 3GB available disk space >> release\README.txt
      shell: cmd
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: release/
        
    - name: List build results
      run: |
        echo "=== Windows build directory contents ==="
        dir app\dist\
        echo "=== Release directory contents ==="
        dir release\
      shell: cmd 