name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        
    - name: Build Windows executable
      run: |
        cd app
        python build_executable.py
        
    - name: Create Windows release package
      run: |
        mkdir release
        
        # 复制Windows可执行文件
        copy "app\dist\剂量验证预测系统.exe" "release\" 2>nul || copy "app\dist\*.exe" "release\"
        
        # 创建Windows使用说明
        echo 剂量验证预测系统 - Windows版本 > release\README.txt
        echo 构建时间: %date% %time% >> release\README.txt
        echo. >> release\README.txt
        echo 使用说明: >> release\README.txt
        echo 1. 下载并解压此文件 >> release\README.txt
        echo 2. 将您的模型文件(result目录)放在可执行文件同一目录下 >> release\README.txt
        echo 3. 双击运行剂量验证预测系统.exe >> release\README.txt
        echo. >> release\README.txt
        echo 注意: 模型文件需要单独提供，不包含在此安装包中 >> release\README.txt
        echo. >> release\README.txt
        echo 系统要求: >> release\README.txt
        echo - Windows 10/11 >> release\README.txt
        echo - 至少4GB内存 >> release\README.txt
        echo - 至少3GB可用磁盘空间 >> release\README.txt
      shell: cmd
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: release/
        
    - name: List build results
      run: |
        echo "=== Windows build directory contents ==="
        dir app\dist\
        echo "=== Release directory contents ==="
        dir release\
      shell: cmd 